/*
 * Copyright (C) 2013-2025 Federico Iosue (developer@omninotes.app)
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

buildscript {
    repositories {
        mavenLocal()
        google()
        mavenCentral()
        maven { url = "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.11.1'
        classpath "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.4.1.3373"
        classpath 'com.adarshr:gradle-test-logger-plugin:4.0.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.20"
    }
    // Exclude the version that the android plugin depends on.
    configurations.classpath.exclude group: 'com.android.tools.external.lombok'
}

allprojects {
    repositories {
        mavenLocal()
        mavenCentral()
        maven { url = "https://jitpack.io" }
        maven { url = "https://plugins.gradle.org/m2/" }
        google()
    }
}

apply plugin: 'org.sonarqube'
sonarqube {
    properties {
        sonar.projectName = "Omni Notes"
        sonar.projectKey = "omni-notes"
        sonar.organization = "federicoiosue-github"
        sonar.projectVersion = project.VERSION_NAME
        sonar.host.url = "https://sonarcloud.io"
        sonar.sourceEncoding = 'UTF-8'
        sonar.language = 'java'
        sonar.coverage.jacoco.xmlReportPaths = "**/build/reports/coverage/**/debug/report.xml"
        sonar.exclusions = '**/src/main/assets/**/*.*'
        sonar.test.exclusions = '**/src/test/**/*.*,**/src/androidTest/**/*.*'
        sonar.gradle.skipCompile = true
    }
}