import kotlin.String

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Update this file with
 *   `$ ./gradlew buildSrcVersions`
 */
object Libs {
    /**
     * http://www.github.com/Shusshu/Android-RecurrencePicker
     */
    const val be_billington_calendar_recurrencepicker_library: String =
            "be.billington.calendar.recurrencepicker:library:" +
            Versions.be_billington_calendar_recurrencepicker_library

    /**
     * http://acra.ch
     */
    const val acra_http: String = "ch.acra:acra-http:" + Versions.ch_acra

    /**
     * http://acra.ch
     */
    const val acra_toast: String = "ch.acra:acra-toast:" + Versions.ch_acra

    /**
     * https://developer.android.com/testing
     */
    const val espresso_core: String = "com.android.support.test.espresso:espresso-core:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val espresso_intents: String = "com.android.support.test.espresso:espresso-intents:" +
            Versions.com_android_support_test_espresso

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_rules: String = "com.android.support.test:rules:" +
            Versions.com_android_support_test

    /**
     * https://developer.android.com/testing
     */
    const val com_android_support_test_runner: String = "com.android.support.test:runner:" +
            Versions.com_android_support_test

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val appcompat_v7: String = "com.android.support:appcompat-v7:" + Versions.appcompat_v7

    /**
     * http://developer.android.com/tools/extras/support-library.html
     */
    const val design: String = "com.android.support:design:" + Versions.design

    const val multidex_instrumentation: String = "com.android.support:multidex-instrumentation:" +
            Versions.multidex_instrumentation

    const val multidex: String = "com.android.support:multidex:" + Versions.multidex

    /**
     * https://developer.android.com/studio
     */
    const val com_android_tools_build_gradle: String = "com.android.tools.build:gradle:" +
            Versions.com_android_tools_build_gradle

    /**
     * https://developer.android.com/studio
     */
    const val lint_gradle: String = "com.android.tools.lint:lint-gradle:" + Versions.lint_gradle

    /**
     * https://github.com/artem-zinnatullin/RxJavaProGuardRules
     */
    const val proguard_rules: String = "com.artemzin.rxjava:proguard-rules:" +
            Versions.proguard_rules

    const val jacoco_android: String = "com.dicedmelon.gradle:jacoco-android:" +
            Versions.jacoco_android

    /**
     * https://github.com/futuresimple/android-floating-action-button
     */
    const val floatingactionbutton: String = "com.getbase:floatingactionbutton:" +
            Versions.floatingactionbutton

    const val commons: String = "com.github.afollestad.material-dialogs:commons:" +
            Versions.com_github_afollestad_material_dialogs

    /**
     * https://af.codes
     */
    const val com_github_afollestad_material_dialogs_core: String =
            "com.github.afollestad.material-dialogs:core:" +
            Versions.com_github_afollestad_material_dialogs

    /**
     * https://github.com/bosphere/Android-FileLogger
     */
    const val filelogger: String = "com.github.bosphere.android-filelogger:filelogger:" +
            Versions.filelogger

    /**
     * https://github.com/bumptech/glide
     */
    const val com_github_bumptech_glide_compiler: String = "com.github.bumptech.glide:compiler:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/bumptech/glide
     */
    const val glide: String = "com.github.bumptech.glide:glide:" +
            Versions.com_github_bumptech_glide

    /**
     * https://github.com/federicoiosue/Omni-Notes-Commons
     */
    const val omni_notes_commons: String = "com.github.federicoiosue:Omni-Notes-Commons:" +
            Versions.omni_notes_commons

    const val springpad_importer: String = "com.github.federicoiosue:Springpad-Importer:" +
            Versions.springpad_importer

    const val analitica: String = "com.github.federicoiosue:analitica:" + Versions.analitica

    /**
     * https://github.com/federicoiosue/checklistview
     */
    const val checklistview: String = "com.github.federicoiosue:checklistview:" +
            Versions.checklistview

    /**
     * https://github.com/federicoiosue/pixlui
     */
    const val pixlui: String = "com.github.federicoiosue:pixlui:" + Versions.pixlui

    /**
     * https://github.com/federicoiosue/simplegallery
     */
    const val simplegallery: String = "com.github.federicoiosue:simplegallery:" +
            Versions.simplegallery

    /**
     * https://github.com/federicoiosue/smart-location-lib
     */
    const val smart_location_lib: String = "com.github.federicoiosue:smart-location-lib:" +
            Versions.smart_location_lib

    /**
     * https://github.com/flavienlaurent/DateTimePicker
     */
    const val com_github_flavienlaurent_datetimepicker_library: String =
            "com.github.flavienlaurent.datetimepicker:library:" +
            Versions.com_github_flavienlaurent_datetimepicker_library

    /**
     * https://github.com/gabrielemariotti/changeloglib
     */
    const val changelog: String = "com.github.gabrielemariotti.changeloglib:changelog:" +
            Versions.changelog

    /**
     * https://github.com/PaoloRotolo/AppIntro
     */
    const val appintro: String = "com.github.paolorotolo:appintro:" + Versions.appintro

    /**
     * http://dashclock.com/api
     */
    const val dashclock_api: String = "com.google.android.apps.dashclock:dashclock-api:" +
            Versions.dashclock_api

    const val play_services_analytics: String = "com.google.android.gms:play-services-analytics:" +
            Versions.play_services_analytics

    /**
     * https://github.com/JakeWharton/timber
     */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * https://github.com/JakeWharton/butterknife/
     */
    const val butterknife_compiler: String = "com.jakewharton:butterknife-compiler:" +
            Versions.com_jakewharton

    /**
     * https://github.com/JakeWharton/butterknife/
     */
    const val butterknife: String = "com.jakewharton:butterknife:" + Versions.com_jakewharton

    /**
     * https://github.com/LarsWerkman/HoloColorPicker
     */
    const val holocolorpicker: String = "com.larswerkman:HoloColorPicker:" +
            Versions.holocolorpicker

    /**
     * https://github.com/nhaarman/ListViewAnimations
     */
    const val lib_core: String = "com.nhaarman.listviewanimations:lib-core:" +
            Versions.com_nhaarman_listviewanimations

    /**
     * https://github.com/nhaarman/ListViewAnimations
     */
    const val lib_manipulation: String = "com.nhaarman.listviewanimations:lib-manipulation:" +
            Versions.com_nhaarman_listviewanimations

    /**
     * https://github.com/pnikosis/materialish-progress
     */
    const val materialish_progress: String = "com.pnikosis:materialish-progress:" +
            Versions.materialish_progress

    /**
     * https://docs.pushbullet.com/extensions
     */
    const val android_extensions: String = "com.pushbullet:android-extensions:" +
            Versions.android_extensions

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android_no_op: String =
            "com.squareup.leakcanary:leakcanary-android-no-op:" + Versions.com_squareup_leakcanary

    /**
     * http://github.com/square/leakcanary/
     */
    const val leakcanary_android: String = "com.squareup.leakcanary:leakcanary-android:" +
            Versions.com_squareup_leakcanary

    /**
     * https://github.com/tbruyelle/RxPermissions
     */
    const val rxpermissions: String = "com.tbruyelle.rxpermissions:rxpermissions:" +
            Versions.rxpermissions

    const val de_fayard_buildsrcversions_gradle_plugin: String =
            "de.fayard.buildSrcVersions:de.fayard.buildSrcVersions.gradle.plugin:" +
            Versions.de_fayard_buildsrcversions_gradle_plugin

    /**
     * https://github.com/greenrobot/EventBus
     */
    const val eventbus: String = "de.greenrobot:eventbus:" + Versions.eventbus

    /**
     * https://github.com/keyboardsurfer/Crouton
     */
    const val crouton: String = "de.keyboardsurfer.android.widget:crouton:" + Versions.crouton

    /**
     * https://github.com/mrmans0n/smart-location-lib
     */
    const val io_nlopez_smartlocation_library: String = "io.nlopez.smartlocation:library:" +
            Versions.io_nlopez_smartlocation_library

    /**
     * https://github.com/ReactiveX/RxAndroid
     */
    const val rxandroid: String = "io.reactivex:rxandroid:" + Versions.rxandroid

    /**
     * https://github.com/ReactiveX/RxJava
     */
    const val rxjava: String = "io.reactivex:rxjava:" + Versions.rxjava

    /**
     * http://junit.org
     */
    const val junit: String = "junit:junit:" + Versions.junit

    /**
     * http://projectlombok.org
     */
    const val lombok_ast: String = "me.tatarka.retrolambda.projectlombok:lombok.ast:" +
            Versions.lombok_ast

    /**
     * https://bitbucket.org/cowwoc/google-diff-match-patch/
     */
    const val diff_match_patch: String = "org.bitbucket.cowwoc:diff-match-patch:" +
            Versions.diff_match_patch

    /**
     * http://ical4j.github.io
     */
    const val ical4j: String = "org.mnode.ical4j:ical4j:" + Versions.ical4j

    /**
     * http://www.mockito.org
     */
    const val mockito_all: String = "org.mockito:mockito-all:" + Versions.mockito_all

    /**
     * http://ocpsoft.org/prettytime/
     */
    const val prettytime: String = "org.ocpsoft.prettytime:prettytime:" + Versions.prettytime

    /**
     * https://github.com/piwik/piwik-sdk-android
     */
    const val piwik_sdk: String = "org.piwik.sdk:piwik-sdk:" + Versions.piwik_sdk

    /**
     * http://www.powermock.org
     */
    const val powermock_api_mockito: String = "org.powermock:powermock-api-mockito:" +
            Versions.org_powermock

    /**
     * http://www.powermock.org
     */
    const val powermock_module_junit4: String = "org.powermock:powermock-module-junit4:" +
            Versions.org_powermock

    /**
     * http://www.powermock.org
     */
    const val powermock: String = "org.powermock:powermock:" + Versions.org_powermock

    /**
     * http://redirect.sonarsource.com/doc/gradle.html
     */
    const val sonarqube_gradle_plugin: String =
            "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:" +
            Versions.sonarqube_gradle_plugin
}
