import kotlin.String
import org.gradle.plugin.use.PluginDependenciesSpec
import org.gradle.plugin.use.PluginDependencySpec

/**
 * Generated by https://github.com/jmfayard/buildSrcVersions
 *
 * Find which updates are available by running
 *     `$ ./gradlew buildSrcVersions`
 * This will only update the comments.
 *
 * YOU are responsible for updating manually the dependency version.
 */
object Versions {
    const val be_billington_calendar_recurrencepicker_library: String = "1.1.1"

    const val ch_acra: String = "5.2.1" // available: "5.4.0"

    const val com_android_support_test_espresso: String = "3.0.2"

    const val com_android_support_test: String = "1.0.2"

    const val appcompat_v7: String = "27.1.1" // available: "28.0.0"

    const val design: String = "27.1.1" // available: "28.0.0"

    const val multidex_instrumentation: String = "1.0.2" // available: "1.0.3"

    const val multidex: String = "1.0.3"

    const val com_android_tools_build_gradle: String = "3.1.4" // available: "3.5.0"

    const val lint_gradle: String = "26.1.4" // available: "26.5.0"

    const val proguard_rules: String = "1.0.14.2" // available: "1.3.3.0"

    const val jacoco_android: String = "0.1.1" // available: "0.1.4"

    const val floatingactionbutton: String = "1.10.1"

    const val com_github_afollestad_material_dialogs: String = "0.8.5.6"

    const val filelogger: String = "1.0.7"

    const val com_github_bumptech_glide: String = "4.8.0" // available: "4.9.0"

    const val omni_notes_commons: String = "1.2.0" // available: "1.3.1"

    const val springpad_importer: String = "1.0.1"

    const val analitica: String = "0.0.3"

    const val checklistview: String = "3.2.1"

    const val pixlui: String = "3.0.0"

    const val simplegallery: String = "3.0.1"

    const val smart_location_lib: String = "3.2.6"

    const val com_github_flavienlaurent_datetimepicker_library: String = "0.0.2"

    const val changelog: String = "2.0.0" // available: "2.1.0"

    const val appintro: String = "1.3.0" // available: "5.1.0"

    const val dashclock_api: String = "2.0.0"

    const val play_services_analytics: String = "9.0.2" // available: "17.0.0"

    const val timber: String = "4.5.1" // available: "4.7.1"

    const val com_jakewharton: String = "8.5.1" // available: "10.1.0"

    const val holocolorpicker: String = "1.4" // available: "1.5"

    const val com_nhaarman_listviewanimations: String = "3.1.0"

    const val materialish_progress: String = "1.5" // available: "1.7"

    const val android_extensions: String = "1.0.4"

    const val com_squareup_leakcanary: String = "1.6.2" // available: "1.6.3"

    const val rxpermissions: String = "0.4.2" // available: "0.9.4"

    const val de_fayard_buildsrcversions_gradle_plugin: String = "0.4.2"

    const val eventbus: String = "2.4.0"

    const val crouton: String = "1.8.4" // available: "1.8.5"

    const val io_nlopez_smartlocation_library: String = "3.2.4" // available: "3.3.3"

    const val rxandroid: String = "1.0.1" // available: "1.2.1"

    const val rxjava: String = "1.0.14" // available: "1.3.8"

    const val junit: String = "4.12"

    const val lombok_ast: String = "0.2.3.a2"

    const val diff_match_patch: String = "1.1" // available: "1.2"

    const val ical4j: String = "1.0.6" // available: "3.0.9"

    const val mockito_all: String = "1.9.5" // available: "1.10.19"

    const val prettytime: String = "3.2.7.Final" // available: "4.0.2.Final"

    const val piwik_sdk: String = "1.0.2" // available: "3.0.4"

    const val org_powermock: String = "1.6.5" // available: "1.7.4"

    const val sonarqube_gradle_plugin: String = "2.6" // available: "2.7.1"

    /**
     *
     * See issue 19: How to update Gradle itself?
     * https://github.com/jmfayard/buildSrcVersions/issues/19
     */
    const val gradleLatestVersion: String = "5.6"

    const val gradleCurrentVersion: String = "4.4"
}

/**
 * See issue #47: how to update buildSrcVersions itself
 * https://github.com/jmfayard/buildSrcVersions/issues/47
 */
val PluginDependenciesSpec.buildSrcVersions: PluginDependencySpec
    inline get() =
            id("de.fayard.buildSrcVersions").version(Versions.de_fayard_buildsrcversions_gradle_plugin)
